# Generated by Django 5.0.6 on 2024-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0002_lecturatemperatura2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTurbinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('turbina1', models.BooleanField(default=False)),
                ('turbina2', models.BooleanField(default=False)),
                ('turbina3', models.BooleanField(default=False)),
                ('turbina4', models.BooleanField(default=False)),
                ('nivel_agua_suficiente', models.BooleanField(default=False)),
            ],
        ),
    ]
