# Generated by Django 5.0.6 on 2024-06-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0003_estadoturbinas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoTurbinas',
        ),
    ]
