# Generated by Django 5.0.6 on 2024-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0004_delete_estadoturbinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMotores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motor1', models.BooleanField(default=False)),
                ('motor2', models.BooleanField(default=False)),
                ('motor3', models.BooleanField(default=False)),
                ('motor4', models.BooleanField(default=False)),
                ('nivel_agua_suficiente', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estado de los Motores',
                'verbose_name_plural': 'Estados de los Motores',
            },
        ),
    ]
