# Generated by Django 5.0.6 on 2024-06-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0005_estadomotores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadomotores',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
