# Generated by Django 5.0.7 on 2024-07-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0006_alter_estadomotores_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturatemperatura',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
